# KeePass Konfiguration

# Topic-Basis
#replace with your own UUID
service.uuid= xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Path to .kdbx file
keepass.file=/your/keepas/file/my-keepass.kdbx

# Master-password
keepass.password=<your keepas password>

