# KeePass Konfiguration

# Topic-Basis
#service.uuid=72385773-1D0E-47E6-ADB8-C6170A9539AE
service.uuid=99656b7d-fde6-4410-81a8-af43e8444b6e

# Path to .kdbx file
keepass.file=/Users/thomasdonhauser/myhome/Projekte/java2/kdbx/iPoxo-IT-GmbH-alias.kdbx

# Master-password
keepass.password=changeme

