# MQTT Broker Configuration
broker.url=ssl://changeme:8883
client.id=plp-backend-client

# Connection params
keepalive.seconds=45
connect.retry.seconds=5

# Broker-Authentication
auth.username=changeme
auth.password=changeme

# Private and public key for package signature
# Use the script generateECCKeyPair.sh to generate the keys
bes.id.dpriv=changeme
bes.id.xpubl=changeme
bes.id.ypubl=changeme

# mTLS client certificate for this serive as a client.
# Verfy it against the PhraseLock-Bridge installtion.
# See https://github.com/phraselock/PhraseLock-Bridge.
tls.client.key=/path/to/certs/mqtt_8883.pkcs8.key
tls.client.cert=/path/to/certs/mqtt_8883.crt