# Psono is still in experimental stage! Do not use it!

# Topic-Basis for Psono
service.uuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

psono.server.url="changeme"
psono.server.publ="changeme"
psono.server.sign="changeme"

psono.api.key="changeme"
psono.api.priv="changeme"
psono.api.secr="changeme"

