# Psono config

# Topic-Basis f�r Psono
service.uuid=1168BB5E-ADEB-4B5B-A0BB-8A06FAB435E3

psono.server.url="changeme"
psono.server.publ="changeme"
psono.server.sign="changeme"

psono.api.key="changeme"
psono.api.priv="changeme"
psono.api.secr="changeme"

